"""Agregar campo password a usuarios

Revision ID: 0b959e32eaf9
Revises: fd35fbb2f7d1
Create Date: 2025-11-09 01:36:55.652112

"""
from alembic import op
import sqlalchemy as sa
from werkzeug.security import generate_password_hash


# revision identifiers, used by Alembic.
revision = '0b959e32eaf9'
down_revision = 'fd35fbb2f7d1'
branch_labels = None
depends_on = None


def upgrade():
    # Agregar columna password como nullable primero
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(), nullable=True))
    
    # Actualizar usuarios existentes con una contraseña temporal
    # IMPORTANTE: Los usuarios deberán cambiar su contraseña
    connection = op.get_bind()
    temp_password_hash = generate_password_hash('temporal123')
    connection.execute(
        sa.text("UPDATE usuarios SET password = :pwd WHERE password IS NULL"),
        {"pwd": temp_password_hash}
    )
    
    # Ahora hacer la columna NOT NULL
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('password', nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('password')

    # ### end Alembic commands ###
