"""Agregar tabla Salas para chats de negociación

Revision ID: 291abd5d0557
Revises: 0b959e32eaf9
Create Date: 2025-11-09 02:19:30.146989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '291abd5d0557'
down_revision = '0b959e32eaf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=False),
    sa.Column('nombre_producto', sa.String(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('precio', sa.Float(), nullable=False),
    sa.Column('condicion', sa.String(), nullable=False),
    sa.Column('creador_id', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['creador_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('salas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_salas_codigo'), ['codigo'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('salas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_salas_codigo'))

    op.drop_table('salas')
    # ### end Alembic commands ###
