"""Agregar tabla MiembroSala para unirse a salas

Revision ID: 79ddbdfd79bb
Revises: 291abd5d0557
Create Date: 2025-11-09 02:51:29.033441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79ddbdfd79bb'
down_revision = '291abd5d0557'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('miembros_sala',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sala_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('fecha_union', sa.DateTime(), nullable=False),
    sa.Column('rol', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['sala_id'], ['salas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sala_id', 'usuario_id', name='unique_miembro_sala')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('miembros_sala')
    # ### end Alembic commands ###
