"""Agregar modelo Transaccion para Open Payments

Revision ID: bfd9ec577e06
Revises: 79ddbdfd79bb
Create Date: 2025-11-09 03:51:05.787224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfd9ec577e06'
down_revision = '79ddbdfd79bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transacciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.String(), nullable=False),
    sa.Column('payment_id', sa.String(), nullable=True),
    sa.Column('sala_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('receiver_wallet', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_completado', sa.DateTime(), nullable=True),
    sa.Column('quote_id', sa.String(), nullable=True),
    sa.Column('interaction_url', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['sala_id'], ['salas.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transacciones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transacciones_transaction_id'), ['transaction_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transacciones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transacciones_transaction_id'))

    op.drop_table('transacciones')
    # ### end Alembic commands ###
